# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [36]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [37]:
### [your code here]
print(np.__version__)
np.show_config()

2.2.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [38]:
### [your code here]
a = np.random.randint(7, size=(2, 3, 5))



### 4. Print a.


In [39]:
### [your code here]
print(a)

[[[3 6 6 5 5]
  [2 4 0 5 0]
  [4 5 2 1 5]]

 [[4 2 4 1 5]
  [4 0 0 3 2]
  [1 0 0 3 4]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [40]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [41]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [42]:
### [your code here]
if a.size == b.size:
    print("They have the same size")
else:
    print("They do not have the same size")

They have the same size



### 8. Are you able to add a and b? Why or why not?


In [43]:
### [your code here]
if a.shape == b.shape:
    print("The can be added because they have the same shape")
else:
    print("The can't be added because they do not have the same shape")
    

The can't be added because they do not have the same shape




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [47]:
### [your code here]
c = np.transpose(b, (1, 2, 0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [77]:
### [your code here]
d = np.add(a,c)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [78]:
### [your code here]

print(a)
print(d)

# Differences: 
# a are integers and 2 are floats

# Similarities
# the shapes are the same

[[[3 6 6 5 5]
  [2 4 0 5 0]
  [4 5 2 1 5]]

 [[4 2 4 1 5]
  [4 0 0 3 2]
  [1 0 0 3 4]]]
[[[4. 7. 7. 6. 6.]
  [3. 5. 1. 6. 1.]
  [5. 6. 3. 2. 6.]]

 [[5. 3. 5. 2. 6.]
  [5. 1. 1. 4. 3.]
  [2. 1. 1. 4. 5.]]]



### 12. Multiply a and c. Assign the result to e.


In [55]:
e = np.add(np.array(a),np.array(c))




### 13. Does e equal to a? Why or why not?


In [64]:
### [your code here]

if np.array_equal(e,a):
    print("They are the same")

else:
    print("They are not the same")
    comparison = a == e
    print("Vergelijking (True/False per element):\n", comparison)
    
# they are not equal becuause the contents dont match up


They are not the same
Vergelijking (True/False per element):
 [[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [66]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [68]:
### [your code here]
f= np.empty





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [74]:
### [your code here]
temp = []
for block in d:
    for row in block:
        for value in row:
            if value == d_min:
                temp.append(0)
            elif value > d_min and value < d_mean:
                temp.append(25)
            elif value == d_mean:
                temp.append(50)
            elif value > d_mean and value < d_max:
                temp.append(75)
            elif value == d_max:
                temp.append(100)
                
            
                
                
f = np.array(temp).reshape(d.shape)  
    





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [75]:
### [your code here]
print(d)   
print(f)   

[[[ 8.  9. 11.  7. 11.]
  [ 7.  5.  1.  9.  3.]
  [ 6.  6.  3.  5. 10.]]

 [[ 8.  9. 11.  7. 11.]
  [ 7.  5.  1.  9.  3.]
  [ 6.  6.  3.  5. 10.]]]
[[[ 75  75 100  75 100]
  [ 75  25   0  75  25]
  [ 25  25  25  25  75]]

 [[ 75  75 100  75 100]
  [ 75  25   0  75  25]
  [ 25  25  25  25  75]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [76]:
### [your code here]
### [your code here]
temp = []
for block in d:
    for row in block:
        for value in row:
            if value == d_min:
                temp.append("A")
            elif value > d_min and value < d_mean:
                temp.append("B")
            elif value == d_mean:
                temp.append("C")
            elif value > d_mean and value < d_max:
                temp.append("D")
            elif value == d_max:
                temp.append("E")
                
            
                
                
f = np.array(temp).reshape(d.shape)  
print(f)

[[['D' 'D' 'E' 'D' 'E']
  ['D' 'B' 'A' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']]

 [['D' 'D' 'E' 'D' 'E']
  ['D' 'B' 'A' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']]]
